version: "3.8"

services:
  valhalla_gis_ops:
    container_name: valhalla_gis-ops
    image: ghcr.io/nilsnolde/docker-valhalla/valhalla:latest
    ports:
      - "8002:8002"
    volumes:
      - valhalla_data:/custom_files
    environment:
      - tile_urls=https://download.geofabrik.de/europe/andorra-latest.osm.pbf
    dns:
      - 8.8.8.8
    restart: unless-stopped

volumes:
  valhalla_data: